language: python

python:
  - 3.6
  - 2.7

sudo: false
before_install:
  - git submodule update --init --recursive

install:
  - pip install -r requirements.txt

script: pytest im

cache:
  directories:
    - $HOME/.cache/pip  # Python packages from pip
